import type { Metadata } from "next";
//👇 Import Open Sans font
import { Open_Sans } from "next/font/google";
import "./globals.css";


//👇 Configure our font object
const openSans = Open_Sans({
 subsets: ['latin'],
 display: 'swap',
});


export const metadata: Metadata = {
 title: "My Profile",
 description: "Generated by create next app",
};


export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
   // 👇 Attach font to global JSX node
   <html lang="en">
     <body className={openSans.className}>{children}</body>
   </html>
 );
}
